# See https://pre-commit.com for more information
repos:
  # from readme - ruff with autofix must run before
  # other formatters, such as black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix , --show-fixes]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
