version: 3

env:
  PYENV: .venv
  PYBIN: '{{.PYENV}}/bin'
  PYTHON: '{{.PYBIN}}/python'
  PRE_COMMIT: '{{.PYBIN}}/pre-commit'

tasks:
  run-linters:
    deps: [ run-black, run-ruff ]

  run-black:
    cmds:
      - .venv/bin/black --target-version py38 .
  run-ruff:
    cmds:
      - .venv/bin/ruff --fix .
